"""Direct loopback full-artifact health; no proxy, redirect or pooled connection.

Every read shares the caller's absolute monotonic deadline. Test-only port
injection stays in this pure adapter; the publisher uses fixed loopback9122.
"""
import hashlib
import re
import socket
import time

MAX_MEMBER=16*1024*1024
MAX_ARTIFACTS=512
MAX_ARCHIVE_BYTES=64*1024*1024
MAX_ROOT_BYTES=MAX_MEMBER
# Generated by release.publish, not part of the ZIP's expanded-byte budget.
# Its bounded SHA/repository/deployment_id JSON is at most 140 bytes today.
MAX_DEPLOYMENT_METADATA_BYTES=256

class Unhealthy(RuntimeError):pass

def remaining(deadline):
 value=deadline-time.monotonic()
 if value<=0:raise Unhealthy('health deadline')
 return value

def validate(hashes):
 if not isinstance(hashes,dict) or not 2<=len(hashes)<=MAX_ARTIFACTS+1 or not {'index.html','_deployment.json'}<=set(hashes):raise Unhealthy('artifact manifest')
 seen=set()
 for name,digest in hashes.items():
  if not isinstance(name,str) or not re.fullmatch(r'[A-Za-z0-9_.\-/]{1,200}',name) or any(p in ('','.','..') for p in name.split('/')) or len(name.split('/'))>2 or ('/' in name and not name.startswith('assets/')) or name.casefold() in seen or name=='manifest.json':raise Unhealthy('artifact name')
  seen.add(name.casefold())
  if not isinstance(digest,str) or not re.fullmatch('[0-9a-f]{64}',digest):raise Unhealthy('artifact digest')

def fetch(path,deadline,port):
 # A fresh socket means no client environment/proxy settings are consulted.
 with socket.create_connection(('127.0.0.1',port),timeout=min(3,remaining(deadline))) as conn:
  conn.settimeout(min(3,remaining(deadline)))
  conn.sendall(('GET /'+path+' HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\nCache-Control: no-cache\r\n\r\n').encode('ascii'))
  raw=bytearray()
  while b'\r\n\r\n' not in raw:
   if len(raw)>=16384:raise Unhealthy('health header bounds')
   conn.settimeout(min(3,remaining(deadline)))
   chunk=conn.recv(min(4096,16384-len(raw)))
   if not chunk:raise Unhealthy('health truncated headers')
   raw.extend(chunk)
  header,body=bytes(raw).split(b'\r\n\r\n',1)
  lines=header.split(b'\r\n')
  if not re.fullmatch(rb'HTTP/1\.[01] 200(?: [^\r\n]*)?',lines[0]):raise Unhealthy('health status')
  headers={}
  for line in lines[1:]:
   if b':' not in line or line.startswith((b' ',b'\t')):raise Unhealthy('health headers')
   key,value=line.split(b':',1);key=key.lower();value=value.strip()
   if key in headers:raise Unhealthy('health duplicate header')
   headers[key]=value
  length=headers.get(b'content-length',b'')
  limit=MAX_DEPLOYMENT_METADATA_BYTES if path=='_deployment.json' else MAX_MEMBER
  if b'transfer-encoding' in headers or not re.fullmatch(rb'[0-9]{1,10}',length) or int(length)>limit:raise Unhealthy('health framing')
  length=int(length)
  if len(body)>length:raise Unhealthy('health extra body')
  digest=hashlib.sha256(body);count=len(body)
  while count<length:
   conn.settimeout(min(3,remaining(deadline)))
   chunk=conn.recv(min(65536,length-count))
   if not chunk:raise Unhealthy('health truncated body')
   count+=len(chunk);digest.update(chunk)
  remaining(deadline)
  return digest.hexdigest(),count

def probe(hashes,deadline,*,port=9122):
 validate(hashes);total=0
 for name,digest in [('',hashes['index.html']),*sorted(hashes.items())]:
  value,size=fetch(name,deadline,port)
  if name=='_deployment.json':limit=MAX_DEPLOYMENT_METADATA_BYTES
  elif name=='':limit=MAX_ROOT_BYTES
  else:
   limit=MAX_MEMBER;total+=size
  if value!=digest or not 0<=size<=limit or total>MAX_ARCHIVE_BYTES:raise Unhealthy('health artifact mismatch/bounds')
 remaining(deadline)
 return True
