import type { MapRecord } from './types';

/** Fixed authored map; forest substitutes for legacy blocking tree/cliff cells. */
export const forestRuins = {
  "id": "map:forest_ruins",
  "width": 12,
  "height": 12,
  "cells": [
    { x: 0, y: 0, elevation: 0, terrainId: "grass" },
    { x: 1, y: 0, elevation: 0, terrainId: "grass" },
    { x: 2, y: 0, elevation: 0, terrainId: "grass" },
    { x: 3, y: 0, elevation: 0, terrainId: "grass" },
    { x: 4, y: 0, elevation: 0, terrainId: "grass" },
    { x: 5, y: 0, elevation: 0, terrainId: "grass" },
    { x: 6, y: 0, elevation: 0, terrainId: "grass" },
    { x: 7, y: 0, elevation: 0, terrainId: "grass" },
    { x: 8, y: 0, elevation: 0, terrainId: "grass" },
    { x: 9, y: 0, elevation: 0, terrainId: "grass" },
    { x: 10, y: 0, elevation: 0, terrainId: "grass" },
    { x: 11, y: 0, elevation: 0, terrainId: "grass" },
    { x: 0, y: 1, elevation: 0, terrainId: "grass" },
    { x: 1, y: 1, elevation: 0, terrainId: "grass" },
    { x: 2, y: 1, elevation: 0, terrainId: "grass" },
    { x: 3, y: 1, elevation: 0, terrainId: "grass" },
    { x: 4, y: 1, elevation: 0, terrainId: "grass" },
    { x: 5, y: 1, elevation: 0, terrainId: "grass" },
    { x: 6, y: 1, elevation: 0, terrainId: "grass" },
    { x: 7, y: 1, elevation: 0, terrainId: "grass" },
    { x: 8, y: 1, elevation: 1, terrainId: "stone" },
    { x: 9, y: 1, elevation: 1, terrainId: "stone" },
    { x: 10, y: 1, elevation: 1, terrainId: "stone" },
    { x: 11, y: 1, elevation: 0, terrainId: "grass" },
    { x: 0, y: 2, elevation: 0, terrainId: "grass" },
    { x: 1, y: 2, elevation: 0, terrainId: "grass" },
    { x: 2, y: 2, elevation: 0, terrainId: "grass" },
    { x: 3, y: 2, elevation: 0, terrainId: "grass" },
    { x: 4, y: 2, elevation: 0, terrainId: "grass" },
    { x: 5, y: 2, elevation: 0, terrainId: "grass" },
    { x: 6, y: 2, elevation: 0, terrainId: "grass" },
    { x: 7, y: 2, elevation: 0, terrainId: "grass" },
    { x: 8, y: 2, elevation: 1, terrainId: "stone" },
    { x: 9, y: 2, elevation: 1, terrainId: "stone" },
    { x: 10, y: 2, elevation: 1, terrainId: "stone" },
    { x: 11, y: 2, elevation: 0, terrainId: "grass" },
    { x: 0, y: 3, elevation: 0, terrainId: "grass" },
    { x: 1, y: 3, elevation: 0, terrainId: "forest" },
    { x: 2, y: 3, elevation: 0, terrainId: "grass" },
    { x: 3, y: 3, elevation: 0, terrainId: "grass" },
    { x: 4, y: 3, elevation: 2, terrainId: "stone" },
    { x: 5, y: 3, elevation: 2, terrainId: "stone" },
    { x: 6, y: 3, elevation: 2, terrainId: "stone" },
    { x: 7, y: 3, elevation: 0, terrainId: "grass" },
    { x: 8, y: 3, elevation: 1, terrainId: "stone" },
    { x: 9, y: 3, elevation: 1, terrainId: "stone" },
    { x: 10, y: 3, elevation: 1, terrainId: "stone" },
    { x: 11, y: 3, elevation: 0, terrainId: "grass" },
    { x: 0, y: 4, elevation: 0, terrainId: "forest" },
    { x: 1, y: 4, elevation: 0, terrainId: "forest" },
    { x: 2, y: 4, elevation: 0, terrainId: "grass" },
    { x: 3, y: 4, elevation: 0, terrainId: "grass" },
    { x: 4, y: 4, elevation: 2, terrainId: "stone" },
    { x: 5, y: 4, elevation: 2, terrainId: "stone" },
    { x: 6, y: 4, elevation: 2, terrainId: "stone" },
    { x: 7, y: 4, elevation: 0, terrainId: "grass" },
    { x: 8, y: 4, elevation: 0, terrainId: "grass" },
    { x: 9, y: 4, elevation: 0, terrainId: "grass" },
    { x: 10, y: 4, elevation: 0, terrainId: "grass" },
    { x: 11, y: 4, elevation: 0, terrainId: "forest" },
    { x: 0, y: 5, elevation: 0, terrainId: "forest" },
    { x: 1, y: 5, elevation: 0, terrainId: "forest" },
    { x: 2, y: 5, elevation: 0, terrainId: "grass" },
    { x: 3, y: 5, elevation: 0, terrainId: "grass" },
    { x: 4, y: 5, elevation: 2, terrainId: "stone" },
    { x: 5, y: 5, elevation: 2, terrainId: "stone" },
    { x: 6, y: 5, elevation: 2, terrainId: "stone" },
    { x: 7, y: 5, elevation: 0, terrainId: "grass" },
    { x: 8, y: 5, elevation: 0, terrainId: "grass" },
    { x: 9, y: 5, elevation: 0, terrainId: "grass" },
    { x: 10, y: 5, elevation: 0, terrainId: "grass" },
    { x: 11, y: 5, elevation: 0, terrainId: "forest" },
    { x: 0, y: 6, elevation: 0, terrainId: "grass" },
    { x: 1, y: 6, elevation: 0, terrainId: "grass" },
    { x: 2, y: 6, elevation: 0, terrainId: "grass" },
    { x: 3, y: 6, elevation: 0, terrainId: "grass" },
    { x: 4, y: 6, elevation: 0, terrainId: "grass" },
    { x: 5, y: 6, elevation: 0, terrainId: "grass" },
    { x: 6, y: 6, elevation: 0, terrainId: "grass" },
    { x: 7, y: 6, elevation: 0, terrainId: "grass" },
    { x: 8, y: 6, elevation: 0, terrainId: "grass" },
    { x: 9, y: 6, elevation: 0, terrainId: "grass" },
    { x: 10, y: 6, elevation: 0, terrainId: "forest" },
    { x: 11, y: 6, elevation: 0, terrainId: "forest" },
    { x: 0, y: 7, elevation: 0, terrainId: "grass" },
    { x: 1, y: 7, elevation: 0, terrainId: "grass" },
    { x: 2, y: 7, elevation: 0, terrainId: "grass" },
    { x: 3, y: 7, elevation: 0, terrainId: "grass" },
    { x: 4, y: 7, elevation: 0, terrainId: "grass" },
    { x: 5, y: 7, elevation: 0, terrainId: "grass" },
    { x: 6, y: 7, elevation: 0, terrainId: "grass" },
    { x: 7, y: 7, elevation: 0, terrainId: "grass" },
    { x: 8, y: 7, elevation: 0, terrainId: "grass" },
    { x: 9, y: 7, elevation: 0, terrainId: "forest" },
    { x: 10, y: 7, elevation: 0, terrainId: "forest" },
    { x: 11, y: 7, elevation: 0, terrainId: "grass" },
    { x: 0, y: 8, elevation: 0, terrainId: "grass_path" },
    { x: 1, y: 8, elevation: 0, terrainId: "grass_path" },
    { x: 2, y: 8, elevation: 1, terrainId: "grass_path" },
    { x: 3, y: 8, elevation: 1, terrainId: "grass_path" },
    { x: 4, y: 8, elevation: 0, terrainId: "grass_path" },
    { x: 5, y: 8, elevation: 0, terrainId: "grass_path" },
    { x: 6, y: 8, elevation: 0, terrainId: "water" },
    { x: 7, y: 8, elevation: 0, terrainId: "water" },
    { x: 8, y: 8, elevation: 0, terrainId: "water" },
    { x: 9, y: 8, elevation: 0, terrainId: "forest" },
    { x: 10, y: 8, elevation: 0, terrainId: "forest" },
    { x: 11, y: 8, elevation: 0, terrainId: "grass" },
    { x: 0, y: 9, elevation: 0, terrainId: "grass" },
    { x: 1, y: 9, elevation: 0, terrainId: "grass" },
    { x: 2, y: 9, elevation: 1, terrainId: "grass" },
    { x: 3, y: 9, elevation: 1, terrainId: "grass" },
    { x: 4, y: 9, elevation: 0, terrainId: "grass" },
    { x: 5, y: 9, elevation: 0, terrainId: "grass" },
    { x: 6, y: 9, elevation: 0, terrainId: "grass" },
    { x: 7, y: 9, elevation: 0, terrainId: "water" },
    { x: 8, y: 9, elevation: 0, terrainId: "grass" },
    { x: 9, y: 9, elevation: 0, terrainId: "grass" },
    { x: 10, y: 9, elevation: 0, terrainId: "grass" },
    { x: 11, y: 9, elevation: 0, terrainId: "grass" },
    { x: 0, y: 10, elevation: 0, terrainId: "grass" },
    { x: 1, y: 10, elevation: 0, terrainId: "grass" },
    { x: 2, y: 10, elevation: 1, terrainId: "grass" },
    { x: 3, y: 10, elevation: 1, terrainId: "grass" },
    { x: 4, y: 10, elevation: 0, terrainId: "grass" },
    { x: 5, y: 10, elevation: 0, terrainId: "grass" },
    { x: 6, y: 10, elevation: 0, terrainId: "grass" },
    { x: 7, y: 10, elevation: 0, terrainId: "grass" },
    { x: 8, y: 10, elevation: 0, terrainId: "grass" },
    { x: 9, y: 10, elevation: 0, terrainId: "grass" },
    { x: 10, y: 10, elevation: 0, terrainId: "grass" },
    { x: 11, y: 10, elevation: 0, terrainId: "grass" },
    { x: 0, y: 11, elevation: 0, terrainId: "grass" },
    { x: 1, y: 11, elevation: 0, terrainId: "grass" },
    { x: 2, y: 11, elevation: 0, terrainId: "grass" },
    { x: 3, y: 11, elevation: 0, terrainId: "grass" },
    { x: 4, y: 11, elevation: 0, terrainId: "grass" },
    { x: 5, y: 11, elevation: 0, terrainId: "grass" },
    { x: 6, y: 11, elevation: 0, terrainId: "grass" },
    { x: 7, y: 11, elevation: 0, terrainId: "grass" },
    { x: 8, y: 11, elevation: 0, terrainId: "grass" },
    { x: 9, y: 11, elevation: 0, terrainId: "grass" },
    { x: 10, y: 11, elevation: 0, terrainId: "grass" },
    { x: 11, y: 11, elevation: 0, terrainId: "grass" }
  ],
  "spawns": [
    {
      "id": 1,
      "side": "heroes",
      "unitId": "fighter",
      "x": 1,
      "y": 8
    },
    {
      "id": 2,
      "side": "heroes",
      "unitId": "ranger",
      "x": 2,
      "y": 8
    },
    {
      "id": 3,
      "side": "heroes",
      "unitId": "mage",
      "x": 1,
      "y": 9
    },
    {
      "id": 4,
      "side": "enemies",
      "unitId": "goblin_grunt",
      "x": 8,
      "y": 4
    },
    {
      "id": 5,
      "side": "enemies",
      "unitId": "goblin_archer",
      "x": 9,
      "y": 2
    },
    {
      "id": 6,
      "side": "enemies",
      "unitId": "goblin_grunt",
      "x": 8,
      "y": 5
    }
  ]
} satisfies MapRecord;
